apiVersion: batch/v1
kind: Job
metadata:
  name: runner
  labels:
    app: runner
spec:
  template:
    spec:
      containers:
      - name: runner
        image: fire015/python-rmi
        imagePullPolicy: IfNotPresent
        command: ["python", "main.py"]
        #command: ["tail", "-f", "/dev/null"]
      restartPolicy: Never
  backoffLimit: 0
